### ISSUE TITLE
Can you explain in words what this does?

### ISSUE THREAD

**Issue by Charuru** [WASasquatch/PPF_Noise_ComfyUI#2]
Examples look wicked sick though.

**Comment by WASasquatch** [comment]
I tried to explain this with "smarts" in the paper in the rep, and have GTP try and fix the grammar and elaborate, but it didn't go that well... however this area at least explains fractal noise well:

> Methodology:
> 
> This section unveils the intricate layers and guiding principles that underpin the Perlin Power Fractal noise algorithm. The algorithm finds its roots in the profound domain of fractal geometry, a mathematical paradigm renowned for its ability to generate > visually captivating and self-similar patterns across varying scales. This segment delves deeply into the algorithm's intricate design and meticulously elucidates its key parameters—each a vital contributor to the algorithm's capacity to produce intricate and > diverse noise patterns.
> Fractal Geometry and Octaves:

> At the heart of the Perlin Power Fractal algorithm lies the fundamental concept of fractal geometry—a conceptual framework celebrated for its capacity to generate intricately detailed and self-consistent patterns across multiple scales. Leveraging the concept > of "octaves," the algorithm introduces nuanced variations at distinct scales. By carefully modulating the frequency and amplitude > of noise, the algorithm seamlessly interweaves intricate details while preserving an overarching coherent structure (subject to parameter tuning).
> Parameterization for Dynamic Noise:

> The Perlin Power Fractal algorithm employs a set of foundational parameters to orchestrate the synthesis of latent noise patterns. > The "persistence" parameter occupies a pivotal role by governing the attenuation of amplitude as octaves progress. This controlled attenuation ensures that minute intricacies remain preserved within the broader context. In contrast, the "lacunarity" parameter plays a complementary role by modulating noise frequency, resulting in a harmonious interplay between local intricacies > and more expansive structural elements.
> Empowering Noise Intensity:

> In the quest to generate visually captivating noise patterns, the algorithm introduces the "exponent" parameter. By subjecting noise values to a power function, this parameter accentuates disparities, yielding an intensified representation of noise intensity. This broad dynamic range of noise values contributes to the diversity of patterns, enriching the visual aesthetics of the resulting images.
> Dimensional Precision through Scaling:

> To traverse the spatial dimensions of the noise patterns, the algorithm incorporates the "scale" parameter. Functioning as a scaling factor, this parameter delineates the dimensions of the generated patterns, thereby influencing noise frequency and amplitude across the image. Consequently, it provides a mechanism for fine-tuning the interplay between intricate details and the > holistic coherence of the pattern.

But with Stable Diffusion, the idea here is that, instead of just creating chaotic noise, with no control, we have Perlin Power Fractals with thousands of combination of parameters for flavored noise, which influences the total generation with KSampler Advanced (with add_noise disabled and using a compatible scheduler and sampler), or influences the base comfy noise if using at the latent input of a normal KSampler (or using add_noise on a KSampler Advanced). 

I was hoping that adding XYZ dimensions for panning the noise, etc, that it would help with animation, but I have yet to test that, and from initial testing, doesn't seem to be the case with how the samplers interpret the noise panning and new noise showing up. I figured it might be helpful with say, a character walking down a street, and the frame panning to the right as the walk, showing, relatively the same composition panning off the frame, and new noise adding new generated compositions. Perhaps I am just using the wrong settings, or there needs to be more control on the KSampler side. 

Anyhow, this is very experimental, and and needs community abuse to figure out all it can, and can't do, or how it could be improved upon.

**Comment by Charuru** [comment]
Thanks!
